In [7]:
#slicing in ndarray

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

ModuleNotFoundError: No module named 'numpy'

In [ ]:
#Slice elements from index 4 to the end of the array:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

ModuleNotFoundError: No module named 'numpy'

In [ ]:
#Slice elements from the beginning to index 4 (not included):

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [ ]:
#-ve slicing

In [ ]:
#Slice from the index 3 from the end to index 1 from the end:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:-1])

[1 2 3 4 5 6]


In [ ]:
#with step

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4:3])

[1 4]


In [ ]:
#Return every other element from the entire array:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [ ]:
# for 2D array

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [ ]:
#From both elements, return index 2:

import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [ ]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 0:3])

[[1 2 3]
 [6 7 8]]
