In [ ]:
#copy and view in numpy

In [2]:
#example for copy
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
x[1] = 22
print(arr)
print(x)

[1 2 3 4 5]
[ 1 22  3  4  5]


In [3]:
#example for copy
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
x[1] = 222
print(arr)
print(x)

[ 1 22  3  4  5]
[ 1 22  3  4  5]


In [3]:
#Print the value of the base attribute to check if an array owns it's data or not:

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]
