Random In python Numpy


From this we use "Random module" which is imported from numpy 


In [1]:
#To import random in code
from numpy import random

We can generate 

--> Random Integer. 

--> Random Float values.

--> Random of our choice.

--> Random in the form of multi dimensional arrays / nd array.


----------------------------------------------------------------------------

For Random integers we use randint(range).

Eg: num = random.randint(100)

op: num b/w (0 to 100)

Note: every thime we execute the code we get new random integer

In [2]:
from numpy import random
num = random.randint(100)
print(f'The random integer: {num}')

The random integer: 94


---

For Random Float values we use rand(size)

Eg num = random.rand(2)

op: [0.121 0.333]

Note it returns values in array format when you pass size as a argument else it just returns random number as a output

In [3]:
from numpy import random
num = random.rand()
print(f'float values: {num}')

float values: 0.3663175034196525


In [4]:
from numpy import random
num = random.rand(5)
print(f"array of float values: {num}")

array of float values: [0.25510106 0.51708451 0.43586695 0.66011275 0.91007548]


---

From Random of our choice we use choice([array of values separated by commas])

eg: num = random.choice([8,5,6,7])

op: 6



In [5]:
from numpy import random
num = random.choice([8,5,6,9,2])
print(f'random choice value: {num}')

random choice value: 6


---

For creating random multi dimensional array 

multi dim with integers or randint()

In [6]:
# with integers
# we use size for it 
# size = (dim,no_of_ele)
#eg:

from numpy import random
num = random.randint(100, size=(3,3))
print(num)

[[69 24 80]
 [66 38 71]
 [ 0 80 69]]


multi dim with float values or rand()

In [7]:
# with float values
# we can directly define dim as first argument and as we already know we alredy have no_of_ele
#eg rand(dim,no_of_ele)

from numpy import random
num = random.rand(3,5)
print(num)

[[0.10412597 0.94894665 0.92820533 0.53734098 0.63735789]
 [0.35208026 0.12676606 0.19271152 0.20590701 0.88895698]
 [0.82950521 0.67159154 0.96929777 0.91910075 0.22102665]]


multi dim with random.choice()

In [8]:
# with choice()
#eg random.choice([array of ele], size = (dim,no_of_ele))


from numpy import random
num = random.choice([8,5,4,2,1], size=(3,5))
print(num)

[[5 2 4 1 8]
 [5 2 5 5 4]
 [4 5 5 2 4]]
